### ISSUE TITLE
Verzija PHP

### ISSUE THREAD

**Issue by Al-bambino** [idusansavic/rafISP#1]
- [x] Koristis tipove kod definisanja varijabli, to postiji tipa od 7.4 verzije PHP-a a mozda ti server tu verziju ne podrzava.
**Resenje**  - Pri definisanju atributa nemoj navoditi kog su tipa, samo navedi vidljivost (kod mene u kodovima nigde nisam navodio tip podatka kod definisanja atributa).
- [x] U klasi `Korisnik` fali `require_once "IzradaListinga.php"; `

Kada sam ovo izmenio usepo sam da pokrenem kod.

**Comment by idusansavic** [comment]
Obrisao tipove kod definisanja varijabli, ali je svakako i mamp i phpstorm na php 7.4.
I dodao require_once "izradaListinga.php" aku u dalje ne mogu da vardumpujem ni jednog ni drugog korisnika. 
Pushovao sam novi kod :/

**Comment by idusansavic** [comment]
> * [x]  Koristis tipove kod definisanja varijabli, to postiji tipa od 7.4 verzije PHP-a a mozda ti server tu verziju ne podrzava.
>   **Resenje**  - Pri definisanju atributa nemoj navoditi kog su tipa, samo navedi vidljivost (kod mene u kodovima nigde nisam navodio tip podatka kod definisanja atributa).
> * [x]  U klasi `Korisnik` fali `require_once "IzradaListinga.php"; `
> 
> Kada sam ovo izmenio usepo sam da pokrenem kod.

Obrisao tipove kod definisanja varijabli, ali je svakako i mamp i phpstorm na php 7.4.
I dodao require_once "izradaListinga.php" aku u dalje ne mogu da vardumpujem ni jednog ni drugog korisnika.
Pushovao sam novi kod :/

**Comment by Al-bambino** [comment]
Klasa `Korisink`:

- [x]  Ostao je tip podatka kod definisanja atributa `$internetProvajder` i `$tarifniPaket`.
- [x]  Metoda `napraviListing` mora da vrati string. Stavi da vraca praza string.

**Comment by idusansavic** [comment]
> Klasa `Korisink`:
> 
> * [x]   Ostao je tip podatka kod definisanja atributa `$internetProvajder` i `$tarifniPaket`.
> * [x]   Metoda `napraviListing` mora da vrati string. Stavi da vraca praza string.

Konacno! Ne znam zasto je bio problem sa varijablama, iako je php 7.4, bukvalno mi nigde nije pokazivao gresku, cak sam i dodao varijable jer mi je pokazivao warning, ali definitivni je bilo zbog metode naprabiListing.

Hvala! Moram se oduziti buretom, jer od hvala nemas nista hahah :D
